### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by NicoKiaru** [trackmate-sc/TrackMate-StarDist#7]
Hello, 

The documentation page returns 404:

https://imagej.net/plugins/trackmate/trackmate-stardist

**Comment by imagejan** [comment]
Fixed in the README now. Any other places where the link broke?

Citing from [this zulip chat](https://imagesc.zulipchat.com/#narrow/stream/327400-TrackMate/topic/Documentation/near/341978754), where @tinevez wrote:

> I hope - but don't really believe - that I did not break any links.

😉

**Comment by NicoKiaru** [comment]
It broke on google, but I guess this will be updated in a while

**Comment by imagejan** [comment]
Maybe some redirects can be put in place on the wiki to rescue the old links? @ctrueden how easy is it to create redirects?

**Comment by tinevez** [comment]
Aw shoot I forgot to update the github repos.

**Comment by ctrueden** [comment]
@imagejan Yes, it can be done with RedirectMatch rules plus ProxyPassMatch exclusions. There are already 2523 redirects and 16 proxy exclusions—what's a few more? I added the following rules for these most recent trackmate page changes:

* /plugins/trackmate/algorithms &rarr; /plugins/trackmate#trackmate-components
* /plugins/trackmate/trackmate-v7-detectors &rarr; /plugins/trackmate/detectors/trackmate-v7-detectors
* /plugins/trackmate/trackmate-display-settings &rarr; /plugins/trackmate/views/trackmate-display-settings
* /plugins/trackmate/custom-actions &rarr; /plugins/trackmate/extending/custom-actions
* /plugins/trackmate/accuracy &rarr; /plugins/trackmate/trackers/accuracy
* /plugins/trackmate/manual-tracking &rarr; /plugins/trackmate/tutorials/manual-tracking
* /plugins/trackmate/custom-track-feature-analyzer-algorithms &rarr; /plugins/trackmate/extending/custom-track-feature-analyzer-algorithms
* /plugins/trackmate/custom-particle-linking-algorithms &rarr; /plugins/trackmate/extending/custom-particle-linking-algorithms
* /plugins/trackmate/custom-viewers &rarr; /plugins/trackmate/extending/custom-viewers
* /plugins/trackmate/custom-segmentation-algorithms &rarr; /plugins/trackmate/extending/custom-segmentation-algorithms
* /plugins/trackmate/custom-spot-feature-analyzer-algorithms &rarr; /plugins/trackmate/extending/custom-spot-feature-analyzer-algorithms
* /plugins/trackmate/manual-track-editing &rarr; /plugins/trackmate/tutorials/manual-track-editing
* /plugins/trackmate/custom-edge-feature-analyzer-algorithms &rarr; /plugins/trackmate/extending/custom-edge-feature-analyzer-algorithms
* /plugins/trackmate/custom-detection-algorithms &rarr; /plugins/trackmate/extending/custom-detection-algorithms
* /plugins/trackmate/scripting &rarr; /plugins/trackmate/scripting/scripting
* /plugins/trackmate/trackmate-detectors-trackers-keys &rarr; /plugins/trackmate/scripting/trackmate-detectors-trackers-keys
* /plugins/trackmate/using-from-matlab &rarr; /plugins/trackmate/scripting/using-from-matlab
* /plugins/trackmate/analyzing-results-with-matlab &rarr; /plugins/trackmate/interoperability/analyzing-results-with-matlab
* /plugins/trackmate/csv-importer &rarr; /plugins/trackmate/extensions/csv-importer
* /plugins/trackmate/faq &rarr; /plugins/trackmate/misc/faq
* /plugins/trackmate/find-maxima-detector &rarr; /plugins/trackmate/extensions/find-maxima-detector
* /plugins/trackmate/getting-started &rarr; /plugins/trackmate/tutorials/getting-started
* /plugins/trackmate/performance &rarr; /plugins/trackmate/detectors/performance
* /plugins/trackmate/trackmate-cellpose &rarr; /plugins/trackmate/detectors/trackmate-cellpose
* /plugins/trackmate/trackmate-ilastik &rarr; /plugins/trackmate/detectors/trackmate-ilastik
* /plugins/trackmate/trackmate-label-image-detector &rarr; /plugins/trackmate/detectors/trackmate-label-image-detector
* /plugins/trackmate/trackmate-mask-detector &rarr; /plugins/trackmate/detectors/trackmate-mask-detector
* /plugins/trackmate/trackmate-morpholibj &rarr; /plugins/trackmate/detectors/trackmate-morpholibj
* /plugins/trackmate/trackmate-oneat &rarr; /plugins/trackmate/extensions/trackmate-oneat
* /plugins/trackmate/trackmate-stardist &rarr; /plugins/trackmate/detectors/trackmate-stardist
* /plugins/trackmate/trackmate-thresholding-detector &rarr; /plugins/trackmate/detectors/trackmate-thresholding-detector
* /plugins/trackmate/trackmate-weka &rarr; /plugins/trackmate/detectors/trackmate-weka
* /plugins/trackmate/trackscheme &rarr; /plugins/trackmate/views/trackscheme
* /plugins/trackmate/version-history &rarr; /plugins/trackmate/misc/version-history

So now e.g. https://imagej.net/TrackScheme and https://imagej.net/plugins/trackmate/trackscheme both still work.

@tinevez Did you know the `nav-links` feature can automatically create the navigation bar from all pages in that particular folder? I noticed that you have all `trackmate/extending` pages have the same navbar to other `trackmate/extending` pages, but you could simplify this to just `nav-links: true` instead of all the hardcoded copies. See [editing/navigation](https://imagej.net/editing/navigation) for details.

Also: would it make sense to add https://pypi.org/project/napatrackmater/ to the list at https://imagej.net/plugins/trackmate/#python ?

**Comment by tinevez** [comment]
> So now e.g. https://imagej.net/TrackScheme and https://imagej.net/plugins/trackmate/trackscheme both still work.

Thank you!

> @tinevez Did you know the `nav-links` feature can automatically create the navigation bar from all pages in that particular folder? I noticed that you have all `trackmate/extending` pages have the same navbar to other `trackmate/extending` pages, but you could simplify this to just `nav-links: true` instead of all the hardcoded copies. See [editing/navigation](https://imagej.net/editing/navigation) for details.

No I did not know! Looks cool.


> Also: would it make sense to add https://pypi.org/project/napatrackmater/ to the list at https://imagej.net/plugins/trackmate/#python ?

But it's already there no?

**Comment by ctrueden** [comment]
> But it's already there no?

@tinevez Ahhh, I can't believe I didn't see it staring right at me! I think I was thrown by the capitalization, and the extra `t` (fixed now).
